### ISSUE TITLE
Support dummy section in configuration

### ISSUE THREAD

**Issue by htfy96** [sjtug/lug#70]
Currently, it is impossible for yaml to define anchors and use them because strict parsing mode prohibits the definition of mixins/anchors.

We propose to support a `dummy` section in top-level configurations, which will not be used in our program. Missing `dummy` section and any value are both valid.

Before:
```yaml
repos:
  - name: a
    conf1: 2
    conf2: 3
  - name: b
    conf1: 2
    conf2: 4
  - name: c
    conf1: 2
    conf3: 5
```

After:
```yaml
dummy:
   common: &common
     conf1: 2
repos:
  - name: a
    <<: *common
    conf2: 3
  - name: b
    <<: *common
    conf2: 4
  - name: c
    <<: *common
    conf3: 5
```
